
services:

  # Microservicio de almacenamiento
  apv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apv
    image: mait-apv:latest
    ports:
      - "5014:8080"

    environment:
      # Base de datos
      - DbOptions__ConnectionString=host = host.docker.internal; Database = apv-db;  username = postgres; Password = malabo-2530;
      - DbOptions__TypeDb=Postgres
      - DbOptions__ConnectionStringBk=host = host.docker.internal; Database = apv-bk;  username = postgres; Password = malabo-2530;
      - DbOptions__TypeDbBk=Postgres
      
      - RabbitMQOptions__HostName=host.docker.internal
      - RabbitMQOptions__Port=5672
      - RabbitMQOptions__UserName=admin
      - RabbitMQOptions__Password=admin
      - RabbitMQOptions__VirtualHost=/
      
      - DOCUMENTAPIOPTIONS__BASEURL=http://document-api:5000
