
services:

  # Microservicio de almacenamiento
  document-serie:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contacts
    image: mait-contacts:latest
    ports:
      - "5014:8080"

    environment:
      # Base de datos
      - AppDbContextFactoryOptions__ConnectionString=host = host.docker.internal; Database = contacts;  username = postgres; Password = malabo-2530;
      - AppDbContextFactoryOptions__TypeDb=Postgres
      - AppDbContextFactoryOptions__ConnectionStringBk=host = host.docker.internal; Database = contacts-bk;  username = postgres; Password = malabo-2530;
      - AppDbContextFactoryOptions__TypeDbBk=Postgres
      
      - RabbitMQOptions__HostName=host.docker.internal
      - RabbitMQOptions__Port=5672
      - RabbitMQOptions__UserName=admin
      - RabbitMQOptions__Password=admin
      - RabbitMQOptions__VirtualHost=/
      
      - DOCUMENTAPIOPTIONS__BASEURL=http://document-api:5000
